sample_names: ["day0-rep1"]

snakemake_min_version: "7.30.1"
mambaforge_version: "23.3.1-0"
seed: 42
timing_repetitions: 5
compression_level: 9
genome_url: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
transcriptome_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_45/gencode.v45.primary_assembly.annotation.gtf.gz"
sirv_set_one_url: "https://www.lexogen.com/wp-content/uploads/2021/06/SIRV_Set1_Norm_Sequences_20210507.zip"
sirv_set_four_url: "https://www.lexogen.com/wp-content/uploads/2021/06/SIRV_Set4_Norm_Sequences_20210507.zip"

sirv_transcriptome_name: "SIRV_ERCC_longSIRV_multi-fasta_20210507.gtf"
sirv_genome_name: "SIRV_ERCC_longSIRV_multi-fasta_20210507.fasta"

align_sort_bam_memory_gb: 4
align_sort_bam_threads: 4
align_map_bam_threads: 12
n_secondary_alignments: 100
illumina_read_length: 150
salmon_index_k: 31
lr_kallisto_index_k: 63
read_name_sam: "qname"

stall_io_threads: 6

discover_isoforms_threads: 12

illumina_trim_min_quality: 20
illumina_trim_min_length: 20

subsample_numbers_sirv: [1]
subsample_read_numbers_sirv: [0.25e+6]
subsample_numbers_gencode: [1]
subsample_read_numbers_gencode: [5.0e+6]

quantify_isoforms_threads: 12

salmon_fragment_length_mean: 250
salmon_fragment_length_sd: 25

liqa_max_distance: 20
liqa_f_weight: 1

kallisto_bus_threshold: 0.8

oarfish_filter_group: "no-filters"
bambu_version: "3.6.0"
